### ISSUE TITLE
Give container a startup delay to allow other containers to start

### ISSUE THREAD

**Issue by minsis** [bitnami/bitnami-docker-haproxy#1]
**Description**

HAProxy containers will crash if the container that HAProxy needs to connect to is not created before the container. Once the container is started you can restart the haproxy container to connect.

There should be a separate wait period maybe that doesn't rely on HAProxy process as DNS will fail and the container crashes.

And yes I realize that I could add a dependency, however, I use a templated docker-compose.yaml file which allows you to enable/disable certain containers based on the server type you're deploying to.

In this context I have zabbix-proxy connecting to HAProxy and HAProxy connects to zabbix-server. In a normal situation zabbix-proxy and zabbix-server are two separate servers, however, we also run this in our dev environment so we enable all containers to run. I can't have zabbix-server depend on haproxy because it doesn't actually depend on it when its on a production server. I also can't have HAProxy depend on zabbix-server because it doesn't normally run on the zabbix-server in production.

Docker has some suggestions on it: https://docs.docker.com/compose/startup-order/

**Steps to reproduce the issue:**

1. ContainerA Depends on HAProxy
2. ContainerB depends on HAProxy
2. HAProxy depends on ContainerA to be up but can't specify that in docker-compose due to separation of servers.

**Describe the results you received:**

HAProxy containers crashes because ContainerA is not running and no DNS exists for it at the time. After ContainerA is started then you can start HAProxy.

**Describe the results you expected:**

HAProxy delays startup by 10-15s while ContainerA is created.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:43:57 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc.)

Server:
 Containers: 8
  Running: 8
  Paused: 0
  Stopped: 0
 Images: 15
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.1.12-124.56.1.el7uek.x86_64
 Operating System: Oracle Linux Server 7.9
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.544GiB
 Name: <hidden>
 ID: <hidden>
 Docker Root Dir: <hiden>
 Debug Mode: false
 HTTP Proxy: <hidden>
 HTTPS Proxy: <hidden>
 No Proxy: <hidden>
 Username: <hidden>
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
VMs

**Comment by rafariossaa** [comment]
Hi,
  I think that for this specific scenario maybe you try to use a script in for the entrypoint where you check what is needed, then call the actual entrypoint. Could you give it a try ?
