### ISSUE TITLE
stats port unable to change

### ISSUE THREAD

**Issue by Cronist** [bitnami/bitnami-docker-haproxy#4]
### Name and Version

bitnami-docker-haproxy

### What is the problem this feature will solve?

unable to overwrite haproxy stats configuration especially name and port. So haproxy conflicts with my other applications and doesn't start on the same docker structure.

### What is the feature you are proposing to solve the problem?

setting an ENV would be perfect.

### What alternatives have you considered?

able to change the stats name and port by commiting.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for requesting this. I am creating an internal task to study it and eventually implement it and produce a new release.
  However, I can not provide an ETA for this. We will come back as soon as we have news.
  Meanwhile, maybe you want to consider sending a PR adding this. We will be glad to review and merge it.
